In [ ]:
print("Hello World!")

Hello World!


In [2]:
x=5
y=6
a="5"
b="5"
print(type(x))
print(type(y))
print(x+y)
print(a+b)

<class 'int'>
<class 'int'>
11
55


In [3]:
#Typecasting
c=int(a)
print(c+x)

10


In [4]:
#List
l1=['hi',1,7,'list',6.7,9.5,[3,45,'hello']]
l2=l1[6][2]
print(l2)
length=len(l1)
print(length)


hello
7


In [ ]:
nums=[]

nums.append(21)
nums.append(40.5)
nums.append("String")

print(nums)

[21, 40.5, 'String']


In [ ]:
#Tuple
t1=(1,2,3,4,5)
print(t1)

(1, 2, 3, 4, 5)


In [8]:
#Dictionary
d1={'Name':'abc', 'Age':'19', 'Proff':'Student'}
print(d1)
print(type(d1))
print(d1.keys())
print(d1.items())
print(d1.values())
print(d1['Name'])

{'Name': 'abc', 'Age': '19', 'Proff': 'Student'}
<class 'dict'>
dict_keys(['Name', 'Age', 'Proff'])
dict_items([('Name', 'abc'), ('Age', '19'), ('Proff', 'Student')])
dict_values(['abc', '19', 'Student'])
abc


In [7]:
# NumPy
import numpy as np

# 2D NumPy array
arr = np.array( [[ 1, 2, 3],
				[ 4, 5, 6]] )

print("Array is of type: ", type(arr))

print("No. of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [9]:
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

arr = np.array((1, 5, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 5 2]


In [6]:
# Function
def sum(array):
	sum = 0
	for i in array:
		sum += i
	return sum

testArray = [1, 3, 34, 22, 49, 48, 20.3]

print('The sum of your numbers is ' + str(sum(testArray)))

The sum of your numbers is 177.3


In [ ]:
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print ("The element wise addition of matrix is : ")
print (np.add(x,y))

print ("The element wise subtraction of matrix is : ")
print (np.subtract(x,y))

print ("The element wise division of matrix is : ")
print (np.divide(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
# Pandas
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [ ]:
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df)

print(df.loc[0])

print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [ ]:
df = pd.read_csv('/content/Data.csv')

print(df.to_string())


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300
